name: gestor_calcados_new
description: App Gestor de Calçados
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localização PT-BR (DatePicker etc.)
  flutter_localizations:
    sdk: flutter

  # Utilidades
  intl: ^0.20.2 # Versão atualizada, mais compatível com Flutter 3.x
  path_provider: ^2.1.5

  # Scanner de código
  mobile_scanner: ^4.0.0

  # PDF / impressão / código de barras
  pdf: ^3.11.3 # Versão ok
  printing: ^5.14.2 # Versão ok
  barcode: ^2.2.8 # Versão ok

  # Banco local (Hive) - VERSÕES ATUALIZADAS
  hive: any
  hive_flutter: any

  # Fontes
  google_fonts: ^6.2.1
  timezone: ^0.9.2 # Versão atualizada para compatibilidade
  file_picker: ^8.0.0
  share_plus: ^7.2.2 # VERSÃO ATUALIZADA
  flutter_colorpicker: ^1.1.0

  # Firebase (APENAS essas linhas):
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # Supabase
  supabase_flutter: ^2.0.0 # Funciona perfeitamente no Windows

  # Gráficos
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # VERSÃO ATUALIZADA E PADRÃO PARA O SEU SDK

  # Dependências para Geração de Código Hive - VERSÕES ATUALIZADAS
  build_runner: ^2.4.8 # Versão atualizada para compatibilidade
  hive_generator: ^2.0.1 # Versão ok
  flutter_launcher_icons: ^0.13.1 # VERSÃO ATUALIZADA

flutter:
  uses-material-design: true

  assets:
    - logo/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "logo/logo_png.png"